version: '3' 
services:
  web:
    image: ${CONTAINER_IMAGE_NAME}
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=compose
    depends_on:
      - redis
    networks:
      - back-tier
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - back-tier
networks:
  back-tier:
    driver: bridge
